# Generated by Django 3.1.3 on 2024-08-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer360', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='social_media',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
