# Generated by Django 3.1.3 on 2024-08-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer360', '0002_auto_20240828_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='social_media',
            field=models.CharField(default='', max_length=200),
        ),
    ]
